/* Generated by MyraPad at 4/18/2024 4:38:02 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace XNAssets.Samples.DdsViewer.UI
{
	partial class MainForm: VerticalStackPanel
	{
		private void BuildUI()
		{
			_textBoxPath = new TextBox();
			_textBoxPath.Readonly = true;
			_textBoxPath.Id = "_textBoxPath";
			StackPanel.SetProportionType(_textBoxPath, Myra.Graphics2D.UI.ProportionType.Fill);

			var label1 = new Label();
			label1.Text = "Browse...";

			_buttonBrowse = new Button();
			_buttonBrowse.Id = "_buttonBrowse";
			_buttonBrowse.Content = label1;

			var label2 = new Label();
			label2.Text = "PositiveX";

			var label3 = new Label();
			label3.Text = "NegativeX";

			var label4 = new Label();
			label4.Text = "PositiveY";

			var label5 = new Label();
			label5.Text = "NegativeY";

			var label6 = new Label();
			label6.Text = "PositiveZ";

			var label7 = new Label();
			label7.Text = "NegativeX";

			_comboCubePlane = new ComboView();
			_comboCubePlane.Id = "_comboCubePlane";
			_comboCubePlane.Widgets.Add(label2);
			_comboCubePlane.Widgets.Add(label3);
			_comboCubePlane.Widgets.Add(label4);
			_comboCubePlane.Widgets.Add(label5);
			_comboCubePlane.Widgets.Add(label6);
			_comboCubePlane.Widgets.Add(label7);

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(_textBoxPath);
			horizontalStackPanel1.Widgets.Add(_buttonBrowse);
			horizontalStackPanel1.Widgets.Add(_comboCubePlane);

			_image = new Image();
			_image.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_image.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_image.Id = "_image";

			_labelType = new Label();
			_labelType.Text = "Type: 2D";
			_labelType.Id = "_labelType";

			_labelFormat = new Label();
			_labelFormat.Text = "Format: Color";
			_labelFormat.Id = "_labelFormat";

			_labelWidth = new Label();
			_labelWidth.Text = "Width: 1024";
			_labelWidth.Id = "_labelWidth";

			_labelHeight = new Label();
			_labelHeight.Text = "Height: 1024";
			_labelHeight.Id = "_labelHeight";

			_labelLevels = new Label();
			_labelLevels.Text = "Levels: 1";
			_labelLevels.Id = "_labelLevels";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			verticalStackPanel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			verticalStackPanel1.Left = -8;
			verticalStackPanel1.Top = -8;
			verticalStackPanel1.Widgets.Add(_labelType);
			verticalStackPanel1.Widgets.Add(_labelFormat);
			verticalStackPanel1.Widgets.Add(_labelWidth);
			verticalStackPanel1.Widgets.Add(_labelHeight);
			verticalStackPanel1.Widgets.Add(_labelLevels);

			var panel1 = new Panel();
			StackPanel.SetProportionType(panel1, Myra.Graphics2D.UI.ProportionType.Fill);
			panel1.Widgets.Add(_image);
			panel1.Widgets.Add(verticalStackPanel1);

			
			Spacing = 8;
			Widgets.Add(horizontalStackPanel1);
			Widgets.Add(panel1);
		}

		
		public TextBox _textBoxPath;
		public Button _buttonBrowse;
		public ComboView _comboCubePlane;
		public Image _image;
		public Label _labelType;
		public Label _labelFormat;
		public Label _labelWidth;
		public Label _labelHeight;
		public Label _labelLevels;
	}
}
