name: Build & Publish Release

on:
  workflow_dispatch:

jobs:
  BuildAndPublish:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: Build XNAssets.MonoGame
      run: dotnet build build/XNAssets.MonoGame.sln --configuration Release
    - name: Build XNAssets.Stride
      run: dotnet build build/XNAssets.Stride.sln --configuration Release
    - name: Test
      run: dotnet test build/XNAssets.MonoGame.sln
    - name: Install NuGet
      uses: NuGet/setup-nuget@v1
    - name: Publish XNAssets.MonoGame to NuGet
      run: nuget.exe push src\XNAssets\bin\MonoGame\Release\XNAssets.MonoGame.*.nupkg ${{secrets.NUGET_APIKEY}} -Source https://api.nuget.org/v3/index.json
    - name: Publish XNAssets.MonoGame.FontStashSharp to NuGet
      run: nuget.exe push src\XNAssets.FontStashSharp\bin\MonoGame\Release\XNAssets.MonoGame.*.nupkg ${{secrets.NUGET_APIKEY}} -Source https://api.nuget.org/v3/index.json
    - name: Publish XNAssets.Stride to NuGet
      run: nuget.exe push src\XNAssets\bin\Stride\Release\XNAssets.Stride.*.nupkg ${{secrets.NUGET_APIKEY}} -Source https://api.nuget.org/v3/index.json
    - name: Publish XNAssets.Stride.FontStashSharp to NuGet
      run: nuget.exe push src\XNAssets.FontStashSharp\bin\Stride\Release\XNAssets.Stride.*.nupkg ${{secrets.NUGET_APIKEY}} -Source https://api.nuget.org/v3/index.json      